
language: swift
osx_image: xcode9.2
xcode_project: Demo.xcworkspace
xcode_scheme: Demo
xcode_sdk: iphonesimulator11.2
sudo: required

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update
  - pod repo update

script:
  - xcodebuild -workspace Demo.xcworkspace -target Demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Demo' -X xcodeplist
